import type { Metadata } from 'next';
import './globals.css';
// import Head from 'next/head'
import { ThemeProvider } from './context/ThemeContext';
import Navbar from './Components/Navbar';
import Footer from './Components/Footer';
import { Toaster } from 'sonner';
// import Head from 'next/head';
import Script from 'next/script';

export const metadata: Metadata = {
	title: 'Charlie B - Jnr Web Dev',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			{/* <Head> */}
			<head>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
				/>

				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
				<link rel="manifest" href="/site.webmanifest" />
				{/* </Head> */}
			</head>
			<Script id="google-tag-manager" strategy="afterInteractive">
				{`
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','${process.env.GOOGLE_ANALYTICS}');
        `}
			</Script>
			<body className="flex flex-col min-h-screen justify-between">
				<ThemeProvider>
					<Navbar />
					<main className="flex-grow mt-24 flex flex-col">{children}</main>
					<Footer />
					<Toaster richColors />
				</ThemeProvider>
				<noscript
					dangerouslySetInnerHTML={{
						__html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${process.env.GOOGLE_ANALYTICS}" height="0" width="0" style="display: none; visibility: hidden;"></iframe>`,
					}}
				/>
			</body>
		</html>
	);
}
