import type { Metadata } from 'next'
import './globals.css'
import Head from 'next/head'
import { Providers } from './Providers'
import  { Inter } from 'next/font/google'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
const inter = Inter({ subsets: ["latin"]})


export const metadata: Metadata = {
  title: 'Charlie B - Jnr Web Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
      {/* <html lang="en" className="light" style={{ colorScheme: 'light' }}> */}
        <Head>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
          <link rel="apple-touch-icon" sizes="180x180" href="src/app/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="src/app/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="src/app/favicon-16x16.png" />
          <link rel="manifest" href="src/app/site.webmanifest" />
        </Head>
        <body className={inter.className}>
            <Providers>
              <Navbar />
              <main>
                {children}
              </main>
              <Footer />
            </Providers>
        </body>
      </html>
    </>
  )
}
